### ISSUE TITLE
News Detail bị lỗi 500

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#10]
Không chạy được news detail

![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/4531dec5-1885-4335-93ce-c42863fb0f3b)

Expected result: status code 200 nếu ra data, hoặc 400 nếu không có
Actual result: status code 500

**Comment by Nguyennm080503** [comment]
Đã fix như bên dưới:
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/750ec975-2fa1-40fc-a44c-18b1e92e9691)
