### ISSUE TITLE
Keyword bị đăt sai tên trong API search news

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#11]
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/5a305c39-2083-400a-b715-ae1ebb41b5f3)

Expected result: Trong request body sẽ có biến keyword dùng để search 
Actual result: Trong request body có biến keywork

**Comment by Nguyennm080503** [comment]
Đã sửa lại biến đúng như expected
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/5f59bcc8-a0ce-42ab-a9ed-4063353adcdd)
