### ISSUE TITLE
Lỗi không upload dialog upload Cloudinary

### ISSUE THREAD

**Issue by Nguyennm080503** [Nguyennm080503/SWD_REAS_2024#15]
Precondition:
- Đăng nhập vào account admin
- Vào phần create news
Step:
- Đăng nhập vào account admin
- Vào phần create news
- Bấm nút Upload File 
- Dialog Upload file Cloudinary
- Close dialog
- Vào phần link khác
- Bấm lại vào phần create news
- Bấm nút Upload file
Actual Result:
- Không hiện dialog Cloudinary
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/fdbcab1b-92d6-4172-82d7-84dc3e78919c)
Expected Result:
- Hiện dialog Cloudinary

**Comment by AlexVo18** [comment]
Đã fix 
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/66e65b71-ced8-470b-958b-5db99f54f490)
