### ISSUE TITLE
Create Auction bị lỗi 400 mặc dù body đầy đủ

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#18]
Create Auction bị lỗi 400 mặc dù body đầy đủ

![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/2d691bc0-b2a8-45d7-a3f7-8228629daf90)
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/24a20779-e035-4dd0-a4aa-bc76f3d0ff99)
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/995da07d-e568-4902-ade8-83aff6420a18)

Expected Result: Response trả 200, data được lưu vào 
Actual Result: Response trả về 400, bị lỗi không lưu được dữ liệu

**Comment by Nguyennm080503** [comment]
Đã fix lỗi: 
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/50fb8efa-1d38-44e5-a4a0-cb1d1bea42f2)
