### ISSUE TITLE
Màn hình hiển thị sai tên status

### ISSUE THREAD

**Issue by Nguyennm080503** [Nguyennm080503/SWD_REAS_2024#19]
Precondition:

Đăng nhập vào account admin
Vào phần deposit management
Step:
Đăng nhập vào account admin
Vào phần deposit management

Actual Result:
Các status đang hiển thị sai
![Screenshot 2024-03-11 221225](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/ada73e79-1ed8-4459-b30c-9645a702fb43)
Expected Result:
Hiện các status name đúng với từng mã status
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/ce4f2a2b-a99f-4e57-b431-0568000ae8c2)

**Comment by AlexVo18** [comment]
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/cce5158c-ff57-4b8e-ae72-54f011061229)
Đã sửa

**Comment by AlexVo18** [comment]
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/07eceba7-d26d-41eb-879b-b9cd5c8aff6f)

Đã sửa
