### ISSUE TITLE
Tạo auction có nhiều photo, nhưng back end chỉ lưu được 1 tấm hình

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#20]
Tạo auction có nhiều photo, nhưng back end chỉ lưu được 1 tấm hình
Request Payload:
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/c181c2cb-8a16-4105-8414-48ca32c3a9b1)
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/539101e0-1157-411a-b372-bec4e929ebff)

Result:
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/6e5920ee-33a1-47ed-9d31-93b566f5418d)

Expected Result: Tất cả bức hình trong array list sẽ được nhận và show ra
Actual Result: Chỉ có đúng 1 bức hình được lưu

**Comment by Nguyennm080503** [comment]
đã fix bug:
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/d0a3977a-e37a-4e98-9877-557eb3ef6809)
