### ISSUE TITLE
SAI LABEL ĐĂNG NHẬP ACCOUNT 

### ISSUE THREAD

**Issue by Nguyennm080503** [Nguyennm080503/SWD_REAS_2024#7]
**Actual Result**: LABEL là Your Email và textbox input có pattern của email

![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/cf67d8fc-cfc3-4068-a6bb-39ba1d7b8bae)
 
**Expected Result**: LABEL là Username và textbox input blank.

**Comment by AlexVo18** [comment]
![Screenshot 2024-02-21 042820](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/9e9a00db-7b1d-4228-88d0-f2b9011bc5c9)
Đã sửa bug UI
