### ISSUE TITLE
Search Real Estates bị lỗi 500

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#8]
Không chạy được search real estates

![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/c1cbc1b5-1bfe-4362-b1bd-6c2758bb1ced)

Expected result: status code 200, có thể ra có data hoặc empty list
Actual result: status code 500

**Comment by Nguyennm080503** [comment]
Đã fix như hình bên dưới :
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/2be7fe17-0688-42bf-ac4f-36e0ab0e23fe)
