### ISSUE TITLE
Real Estate Detail bị lỗi 500

### ISSUE THREAD

**Issue by AlexVo18** [Nguyennm080503/SWD_REAS_2024#9]
Không chạy được real estate detail

![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/139372983/2a045f03-b8db-40a6-9cda-db13af4ea55a)

Expected result: status code 200 nếu ra data, hoặc 400 nếu không có
Actual result: status code 500

**Comment by Nguyennm080503** [comment]
Đã fix như hình bên dưới 
![image](https://github.com/Nguyennm080503/SWD_REAS_2024/assets/108600635/5409dc9c-f18d-418e-a9d4-0f4370914109)
